name: Auto Fix and Lint Workflow

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  lint-and-fix:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 black isort

      - name: Run auto-fix with Black and Isort
        run: |
          black . --check || black .
          isort . --check-only || isort .
      
      - name: Run Flake8 (lint check only)
        run: flake8 .

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto-fix lint errors [bot]" || echo "No changes to commit"
          git push origin HEAD:${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
